### ISSUE TITLE
Implement the login

### ISSUE THREAD

**Issue by faouziamrouche** [faouziamrouche/Fahemni#1]
I would like to implement the system for the login of the user and to display the data to the user in a "personal information" web page which is like a control panel.

**Comment by shreyanshdwivedi** [comment]
@faouziamrouche, can you please tell if u want to implement login in backend as well as frontend or only frontend? If both then in which backend language do u want to implement login

**Comment by faouziamrouche** [comment]
@shreyanshdwivedi, I'd like to implement it both in the front-end and in the back-end with php ideally. If you could do both that would be cool

**Comment by Markandeya** [comment]
Is this assigned? If not, I would like to work on it.

**Comment by faouziamrouche** [comment]
@Markandeya, it's not assigned yet, you are welcome to work on it.

**Comment by Markandeya** [comment]
@faouziamrouche  Great!

**Comment by Markandeya** [comment]
@faouziamrouche  I have created the login page and a dummy landing page with logout.

**Comment by shreyanshdwivedi** [comment]
@faouziamrouche please review PR of @Markandeya so that I can use his config file for my issue #2 ..

**Comment by faouziamrouche** [comment]
done

**Comment by faouziamrouche** [comment]
@shreyanshdwivedi , it's done
