### ISSUE TITLE
Posting videos

### ISSUE THREAD

**Issue by faouziamrouche** [faouziamrouche/Fahemni#2]
i would like to add the "video post" feature to the website which is an open source e-learning website based on videos. The videos are uploaded and stored directly on Youtube, and displayed on the website.

**Comment by AmanYdv20** [comment]
i'll like to work on it.

**Comment by faouziamrouche** [comment]
@Avnish1234, you're welcome to do so

**Comment by shreyanshdwivedi** [comment]
@faouziamrouche, is this assigned yet?
I will like to work on it..

**Comment by faouziamrouche** [comment]
@shreyanshdwivedi, you're welcome

**Comment by shreyanshdwivedi** [comment]
@faouziamrouche, please correct me if I am wrong.
You want that video content page when anyone click on the subject in content section.
Should I create a new dynamic page which gets the link clicked by user and the show videos accordingly?

**Comment by faouziamrouche** [comment]
@shreyanshdwivedi, you're right. The website contains a lot of videos classified by categories, and the are displayed in the home page, and each category has a number of videos related to it. So when the user selects a category, the website redirects him to a new page where the videos are displayed, and when he clicks on a video, it takes him to another page to visualize the video. The categories, and the videos are classified inside of the database. But the videos are not stored in the website but directly in Youtube.

**Comment by shreyanshdwivedi** [comment]
@faouziamrouche I am working on this and will keep you updated

**Comment by shreyanshdwivedi** [comment]
@faouziamrouche I'll update you in 2 to 3 days
